### ISSUE TITLE
Using The Dataset

### ISSUE THREAD

**Issue by slerman12** [tcl326/relation-networks#2]
Hi, I'm trying to find a source for the Sort-of-CLEVR Dataset. The provided code in this repository seems to be what I'm looking for, but I need help understanding how to set it up for training, validation, and testing. Could you provide a brief example of how the included code could be used to generate a training, validation, and testing set, and then from this, iterate through these datasets in batches of chosen size?

**Comment by tcl326** [comment]
You can have a look at my Jupyter notebook [example](https://github.com/tcl326/relation-networks/blob/master/A%20Simple%20Neural%20Network%20Module%20for%20Relational%20Reasoning.ipynb))
